package net.imed_portal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-09-13T17:54:46.520+01:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://www.imed-portal.net/", name = "MonitorSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface MonitorSoap {

    @WebResult(name = "LOGGED_INResult", targetNamespace = "http://www.imed-portal.net/")
    @RequestWrapper(localName = "LOGGED_IN", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.LOGGEDIN")
    @WebMethod(operationName = "LOGGED_IN", action = "http://www.imed-portal.net/LOGGED_IN")
    @ResponseWrapper(localName = "LOGGED_INResponse", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.LOGGEDINResponse")
    public boolean loggedIN(
        @WebParam(name = "US_ID_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String usIDIN,
        @WebParam(name = "PW_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String pwIN
    );

    @WebResult(name = "PUT_HEARTBEAT_PULSEResult", targetNamespace = "http://www.imed-portal.net/")
    @RequestWrapper(localName = "PUT_HEARTBEAT_PULSE", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.PUTHEARTBEATPULSE")
    @WebMethod(operationName = "PUT_HEARTBEAT_PULSE", action = "http://www.imed-portal.net/PUT_HEARTBEAT_PULSE")
    @ResponseWrapper(localName = "PUT_HEARTBEAT_PULSEResponse", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.PUTHEARTBEATPULSEResponse")
    public boolean putHEARTBEATPULSE(
        @WebParam(name = "IN_REFNUM_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String inREFNUMIN
    );

    @WebResult(name = "GET_STATUSCHECK_FREQUENCYResult", targetNamespace = "http://www.imed-portal.net/")
    @RequestWrapper(localName = "GET_STATUSCHECK_FREQUENCY", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.GETSTATUSCHECKFREQUENCY")
    @WebMethod(operationName = "GET_STATUSCHECK_FREQUENCY", action = "http://www.imed-portal.net/GET_STATUSCHECK_FREQUENCY")
    @ResponseWrapper(localName = "GET_STATUSCHECK_FREQUENCYResponse", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.GETSTATUSCHECKFREQUENCYResponse")
    public int getSTATUSCHECKFREQUENCY(
        @WebParam(name = "IN_REFNUM_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String inREFNUMIN
    );

    @WebResult(name = "GET_HEARTBEAT_FREQUENCYResult", targetNamespace = "http://www.imed-portal.net/")
    @RequestWrapper(localName = "GET_HEARTBEAT_FREQUENCY", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.GETHEARTBEATFREQUENCY")
    @WebMethod(operationName = "GET_HEARTBEAT_FREQUENCY", action = "http://www.imed-portal.net/GET_HEARTBEAT_FREQUENCY")
    @ResponseWrapper(localName = "GET_HEARTBEAT_FREQUENCYResponse", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.GETHEARTBEATFREQUENCYResponse")
    public int getHEARTBEATFREQUENCY(
        @WebParam(name = "IN_REFNUM_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String inREFNUMIN
    );

    @WebResult(name = "PUT_SUPPORT_REQUESTResult", targetNamespace = "http://www.imed-portal.net/")
    @RequestWrapper(localName = "PUT_SUPPORT_REQUEST", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.PUTSUPPORTREQUEST")
    @WebMethod(operationName = "PUT_SUPPORT_REQUEST", action = "http://www.imed-portal.net/PUT_SUPPORT_REQUEST")
    @ResponseWrapper(localName = "PUT_SUPPORT_REQUESTResponse", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.PUTSUPPORTREQUESTResponse")
    public boolean putSUPPORTREQUEST(
        @WebParam(name = "SU_INREFNUM_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String suINREFNUMIN,
        @WebParam(name = "SU_SEVERITY_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String suSEVERITYIN,
        @WebParam(name = "SU_CONTACT_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String suCONTACTIN,
        @WebParam(name = "SU_EMAIL_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String suEMAILIN,
        @WebParam(name = "SU_TELNO_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String suTELNOIN,
        @WebParam(name = "SU_MESSAGE_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String suMESSAGEIN
    );

    @WebResult(name = "IS_REPORTING_AVAILABLEResult", targetNamespace = "http://www.imed-portal.net/")
    @RequestWrapper(localName = "IS_REPORTING_AVAILABLE", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.ISREPORTINGAVAILABLE")
    @WebMethod(operationName = "IS_REPORTING_AVAILABLE", action = "http://www.imed-portal.net/IS_REPORTING_AVAILABLE")
    @ResponseWrapper(localName = "IS_REPORTING_AVAILABLEResponse", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.ISREPORTINGAVAILABLEResponse")
    public boolean isREPORTINGAVAILABLE(
        @WebParam(name = "IN_REFNUM_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String inREFNUMIN
    );

    @WebResult(name = "PUT_FEEDBACKResult", targetNamespace = "http://www.imed-portal.net/")
    @RequestWrapper(localName = "PUT_FEEDBACK", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.PUTFEEDBACK")
    @WebMethod(operationName = "PUT_FEEDBACK", action = "http://www.imed-portal.net/PUT_FEEDBACK")
    @ResponseWrapper(localName = "PUT_FEEDBACKResponse", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.PUTFEEDBACKResponse")
    public boolean putFEEDBACK(
        @WebParam(name = "FB_INREFNUM_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String fbINREFNUMIN,
        @WebParam(name = "FB_CONTACT_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String fbCONTACTIN,
        @WebParam(name = "FB_EMAIL_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String fbEMAILIN,
        @WebParam(name = "FB_MESSAGE_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String fbMESSAGEIN,
        @WebParam(name = "FB_TELNO_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String fbTELNOIN
    );

    @WebResult(name = "PUT_STATUSCHECK_PACKETResult", targetNamespace = "http://www.imed-portal.net/")
    @RequestWrapper(localName = "PUT_STATUSCHECK_PACKET", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.PUTSTATUSCHECKPACKET")
    @WebMethod(operationName = "PUT_STATUSCHECK_PACKET", action = "http://www.imed-portal.net/PUT_STATUSCHECK_PACKET")
    @ResponseWrapper(localName = "PUT_STATUSCHECK_PACKETResponse", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.PUTSTATUSCHECKPACKETResponse")
    public boolean putSTATUSCHECKPACKET(
        @WebParam(name = "IN_REFNUM_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String inREFNUMIN,
        @WebParam(name = "DISK0_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String disk0IN,
        @WebParam(name = "DISK1_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String disk1IN,
        @WebParam(name = "DISK2_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String disk2IN,
        @WebParam(name = "DISK3_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String disk3IN,
        @WebParam(name = "DISK4_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String disk4IN,
        @WebParam(name = "TEMP_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String tempIN,
        @WebParam(name = "UPTIME_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String uptimeIN,
        @WebParam(name = "PATIENTS_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String patientsIN,
        @WebParam(name = "REFERRALS_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String referralsIN,
        @WebParam(name = "REFERALLSLASTHOUR_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String referallslasthourIN,
        @WebParam(name = "USERS_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String usersIN,
        @WebParam(name = "USERSLASTHOUR_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String userslasthourIN
    );

    @WebResult(name = "IS_SERVICE_AVAILABLEResult", targetNamespace = "http://www.imed-portal.net/")
    @RequestWrapper(localName = "IS_SERVICE_AVAILABLE", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.ISSERVICEAVAILABLE")
    @WebMethod(operationName = "IS_SERVICE_AVAILABLE", action = "http://www.imed-portal.net/IS_SERVICE_AVAILABLE")
    @ResponseWrapper(localName = "IS_SERVICE_AVAILABLEResponse", targetNamespace = "http://www.imed-portal.net/", className = "net.imed_portal.ISSERVICEAVAILABLEResponse")
    public boolean isSERVICEAVAILABLE(
        @WebParam(name = "IN_REFNUM_IN", targetNamespace = "http://www.imed-portal.net/")
        java.lang.String inREFNUMIN
    );
}
