package net.imed_portal;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-09-13T17:54:46.559+01:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "Monitor", 
                  wsdlLocation = "http://www.imed-portal.net/cievert_monitor_ws/monitor.asmx?wsdl",
                  targetNamespace = "http://www.imed-portal.net/") 
public class Monitor extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.imed-portal.net/", "Monitor");
    public final static QName MonitorSoap = new QName("http://www.imed-portal.net/", "MonitorSoap");
    public final static QName MonitorSoap12 = new QName("http://www.imed-portal.net/", "MonitorSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://www.imed-portal.net/cievert_monitor_ws/monitor.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Monitor.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.imed-portal.net/cievert_monitor_ws/monitor.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Monitor(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Monitor(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Monitor() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns MonitorSoap
     */
    @WebEndpoint(name = "MonitorSoap")
    public MonitorSoap getMonitorSoap() {
        return super.getPort(MonitorSoap, MonitorSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MonitorSoap
     */
    @WebEndpoint(name = "MonitorSoap")
    public MonitorSoap getMonitorSoap(WebServiceFeature... features) {
        return super.getPort(MonitorSoap, MonitorSoap.class, features);
    }
    /**
     *
     * @return
     *     returns MonitorSoap
     */
    @WebEndpoint(name = "MonitorSoap12")
    public MonitorSoap getMonitorSoap12() {
        return super.getPort(MonitorSoap12, MonitorSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MonitorSoap
     */
    @WebEndpoint(name = "MonitorSoap12")
    public MonitorSoap getMonitorSoap12(WebServiceFeature... features) {
        return super.getPort(MonitorSoap12, MonitorSoap.class, features);
    }

}
